### PR TITLE
Feature/drawer current user header

### PR DESCRIPTION
**Pull request by KishoreBabuIN**
Show the current logged in user's image and name, on the drawer header.

### CODE REVIEW

**Review by nikhilbansal97 — DISMISSED** [review]
There is an error in the drawer. `The getter avatarUrl was called on a null receiver`

**Comment by nikhilbansal97** [comment]
Here is screenshot of the bug
screenshot_1537459887

**Comment by oianmol** [comment]
@barykaed **can we fix this ?** 
:heart_eyes: :stuck_out_tongue_winking_eye:
_Sent from my Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nikhilbansal97** [comment]
Working on it

**Comment by oianmol** [comment]
@nikhilbansal97 is this fixed ?

**Comment by nikhilbansal97** [comment]
Yes, pushing the code now

**Pull request merged**
