### PR TITLE
added organization and starred repos api

### PR DESCRIPTION
**Pull request by oianmol**

### CODE REVIEW

**Comment by nikhilbansal97** [comment]
@Anmol92verma I don't see any option to see the organizations or starred repos 🤷🏻‍♂️

**Comment by oianmol** [comment]
@nikhilbansal97 the api for org and starred repos is written in github.dart . Can’t you see that in the commit ?

**Comment by nikhilbansal97** [comment]
I meant in the app. There is no option to see the organizations and starred repos in the app.

**Comment by oianmol** [comment]
Yes bhai! That will be added with the view

**Review by nikhilbansal97 — APPROVED** [review]

**Pull request merged**
